name: Feature Request
description: Request a new feature or suggest a change
title: '[feature] SHORT DESCRIPTION'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a request.
        **Please don't forget to update the issue title.**
  - type: textarea
    id: suggestion
    attributes:
      label: What is your suggestion?
      description: Please be as specific as possible!
      placeholder: Hi! I would like for patch-ng to be able to ...
    validations:
      required: true
