name: Build patch exe for Windows

on: workflow_dispatch

jobs:
  windows_exe:
    name: Create windows executable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: x64
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: patch_ng.py
          mode: onefile
          output-dir: build
          output-file: patch.exe
      - uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/patch.exe
          include-hidden-files: true
