name: Main workflow

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
      - 'LICENSE'
      - 'example/**'
      - '.gitignore'
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
      - 'LICENSE'
      - 'example/**'
      - '.gitignore'


jobs:
  linux-validate:
    name: Validate on Linux - Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.6.15', '3.8.18', '3.12.11' ]
    steps:
      - uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Run tests
        run: python tests/run_tests.py

  windows-validate:
    name: Validate on Windows - Python ${{ matrix.python }}
    runs-on: windows-latest
    strategy:
      matrix:
        python: [ '3.6.15', '3.8.18', '3.12.11' ]
    steps:
      - uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Run tests
        run: python tests/run_tests.py
